version: 2
updates:
  - package-ecosystem: bun
    directory: /solana
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /solana
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
