[package]
name         = "timba"
version      = "0.1.2"
description  = "Created with Anchor"
edition      = "2021"

[lib]
crate-type = ["cdylib"]
name = "timba"

[features]
default = ["no-idl", "no-log-ix-name"]
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = [
  "anchor-lang/idl-build",
  "anchor-spl/idl-build",
  "anchor-spl/token_2022",
]

[dependencies]
anchor-lang = { workspace = true }
anchor-spl  = { workspace = true, features = ["token", "associated_token", "token_2022"] }
solana-sha256-hasher = { workspace = true }
